const j = [
  {
    id: '538995f1eb11573a',
    type: 'tab',
    label: 'reCamera Dashboard',
    disabled: false,
    info: '',
    env: [],
  },
  {
    id: 'ed8eabb66a7d65e6',
    type: 'camera',
    z: '538995f1eb11573a',
    client: '9669d4dcfa771f83',
    audio: false,
    volume: '50',
    option: '0',
    x: 240,
    y: 120,
    wires: [['57e1fa1fdbf4161a']],
  },
  {
    id: '57e1fa1fdbf4161a',
    type: 'model',
    z: '538995f1eb11573a',
    name: 'model',
    uri: '/usr/share/supervisor/models/yolo11n_classify_cv181x_int8.cvimodel',
    model: 'YOLO11n Classify',
    tscore: '0.01',
    tiou: '0.01',
    debug: false,
    trace: false,
    counting: false,
    draw: false,
    classes:
      "tench,goldfish,great_white_shark,tiger_shark,hammerhead,electric_ray,stingray,cock,hen,ostrich,brambling,goldfinch,house_finch,junco,indigo_bunting,robin,bulbul,jay,magpie,chickadee,water_ouzel,kite,bald_eagle,vulture,great_grey_owl,European_fire_salamander,common_newt,eft,spotted_salamander,axolotl,bullfrog,tree_frog,tailed_frog,loggerhead,leatherback_turtle,mud_turtle,terrapin,box_turtle,banded_gecko,common_iguana,American_chameleon,whiptail,agama,frilled_lizard,alligator_lizard,Gila_monster,green_lizard,African_chameleon,Komodo_dragon,African_crocodile,American_alligator,triceratops,thunder_snake,ringneck_snake,hognose_snake,green_snake,king_snake,garter_snake,water_snake,vine_snake,night_snake,boa_constrictor,rock_python,Indian_cobra,green_mamba,sea_snake,horned_viper,diamondback,sidewinder,trilobite,harvestman,scorpion,black_and_gold_garden_spider,barn_spider,garden_spider,black_widow,tarantula,wolf_spider,tick,centipede,black_grouse,ptarmigan,ruffed_grouse,prairie_chicken,peacock,quail,partridge,African_grey,macaw,sulphur-crested_cockatoo,lorikeet,coucal,bee_eater,hornbill,hummingbird,jacamar,toucan,drake,red-breasted_merganser,goose,black_swan,tusker,echidna,platypus,wallaby,koala,wombat,jellyfish,sea_anemone,brain_coral,flatworm,nematode,conch,snail,slug,sea_slug,chiton,chambered_nautilus,Dungeness_crab,rock_crab,fiddler_crab,king_crab,American_lobster,spiny_lobster,crayfish,hermit_crab,isopod,white_stork,black_stork,spoonbill,flamingo,little_blue_heron,American_egret,bittern,crane_(bird),limpkin,European_gallinule,American_coot,bustard,ruddy_turnstone,red-backed_sandpiper,redshank,dowitcher,oystercatcher,pelican,king_penguin,albatross,grey_whale,killer_whale,dugong,sea_lion,Chihuahua,Japanese_spaniel,Maltese_dog,Pekinese,Shih-Tzu,Blenheim_spaniel,papillon,toy_terrier,Rhodesian_ridgeback,Afghan_hound,basset,beagle,bloodhound,bluetick,black-and-tan_coonhound,Walker_hound,English_foxhound,redbone,borzoi,Irish_wolfhound,Italian_greyhound,whippet,Ibizan_hound,Norwegian_elkhound,otterhound,Saluki,Scottish_deerhound,Weimaraner,Staffordshire_bullterrier,American_Staffordshire_terrier,Bedlington_terrier,Border_terrier,Kerry_blue_terrier,Irish_terrier,Norfolk_terrier,Norwich_terrier,Yorkshire_terrier,wire-haired_fox_terrier,Lakeland_terrier,Sealyham_terrier,Airedale,cairn,Australian_terrier,Dandie_Dinmont,Boston_bull,miniature_schnauzer,giant_schnauzer,standard_schnauzer,Scotch_terrier,Tibetan_terrier,silky_terrier,soft-coated_wheaten_terrier,West_Highland_white_terrier,Lhasa,flat-coated_retriever,curly-coated_retriever,golden_retriever,Labrador_retriever,Chesapeake_Bay_retriever,German_short-haired_pointer,vizsla,English_setter,Irish_setter,Gordon_setter,Brittany_spaniel,clumber,English_springer,Welsh_springer_spaniel,cocker_spaniel,Sussex_spaniel,Irish_water_spaniel,kuvasz,schipperke,groenendael,malinois,briard,kelpie,komondor,Old_English_sheepdog,Shetland_sheepdog,collie,Border_collie,Bouvier_des_Flandres,Rottweiler,German_shepherd,Doberman,miniature_pinscher,Greater_Swiss_Mountain_dog,Bernese_mountain_dog,Appenzeller,EntleBucher,boxer,bull_mastiff,Tibetan_mastiff,French_bulldog,Great_Dane,Saint_Bernard,Eskimo_dog,malamute,Siberian_husky,dalmatian,affenpinscher,basenji,pug,Leonberg,Newfoundland,Great_Pyrenees,Samoyed,Pomeranian,chow,keeshond,Brabancon_griffon,Pembroke,Cardigan,toy_poodle,miniature_poodle,standard_poodle,Mexican_hairless,timber_wolf,white_wolf,red_wolf,coyote,dingo,dhole,African_hunting_dog,hyena,red_fox,kit_fox,Arctic_fox,grey_fox,tabby,tiger_cat,Persian_cat,Siamese_cat,Egyptian_cat,cougar,lynx,leopard,snow_leopard,jaguar,lion,tiger,cheetah,brown_bear,American_black_bear,ice_bear,sloth_bear,mongoose,meerkat,tiger_beetle,ladybug,ground_beetle,long-horned_beetle,leaf_beetle,dung_beetle,rhinoceros_beetle,weevil,fly,bee,ant,grasshopper,cricket,walking_stick,cockroach,mantis,cicada,leafhopper,lacewing,dragonfly,damselfly,admiral,ringlet,monarch,cabbage_butterfly,sulphur_butterfly,lycaenid,starfish,sea_urchin,sea_cucumber,wood_rabbit,hare,Angora,hamster,porcupine,fox_squirrel,marmot,beaver,guinea_pig,sorrel,zebra,hog,wild_boar,warthog,hippopotamus,ox,water_buffalo,bison,ram,bighorn,ibex,hartebeest,impala,gazelle,Arabian_camel,llama,weasel,mink,polecat,black-footed_ferret,otter,skunk,badger,armadillo,three-toed_sloth,orangutan,gorilla,chimpanzee,gibbon,siamang,guenon,patas,baboon,macaque,langur,colobus,proboscis_monkey,marmoset,capuchin,howler_monkey,titi,spider_monkey,squirrel_monkey,Madagascar_cat,indri,Indian_elephant,African_elephant,lesser_panda,giant_panda,barracouta,eel,coho,rock_beauty,anemone_fish,sturgeon,gar,lionfish,puffer,abacus,abaya,academic_gown,accordion,acoustic_guitar,aircraft_carrier,airliner,airship,altar,ambulance,amphibian,analog_clock,apiary,apron,ashcan,assault_rifle,backpack,bakery,balance_beam,balloon,ballpoint,Band_Aid,banjo,bannister,barbell,barber_chair,barbershop,barn,barometer,barrel,barrow,baseball,basketball,bassinet,bassoon,bathing_cap,bath_towel,bathtub,beach_wagon,beacon,beaker,bearskin,beer_bottle,beer_glass,bell_cote,bib,bicycle-built-for-two,bikini,binder,binoculars,birdhouse,boathouse,bobsled,bolo_tie,bonnet,bookcase,bookshop,bottlecap,bow,bow_tie,brass,brassiere,breakwater,breastplate,broom,bucket,buckle,bulletproof_vest,bullet_train,butcher_shop,cab,caldron,candle,cannon,canoe,can_opener,cardigan,car_mirror,carousel,carpenter,s_kit,carton,car_wheel,cash_machine,cassette,cassette_player,castle,catamaran,CD_player,cello,cellular_telephone,chain,chainlink_fence,chain_mail,chain_saw,chest,chiffonier,chime,china_cabinet,Christmas_stocking,church,cinema,cleaver,cliff_dwelling,cloak,clog,cocktail_shaker,coffee_mug,coffeepot,coil,combination_lock,computer_keyboard,confectionery,container_ship,convertible,corkscrew,cornet,cowboy_boot,cowboy_hat,cradle,crane_(machine),crash_helmet,crate,crib,Crock_Pot,croquet_ball,crutch,cuirass,dam,desk,desktop_computer,dial_telephone,diaper,digital_clock,digital_watch,dining_table,dishrag,dishwasher,disk_brake,dock,dogsled,dome,doormat,drilling_platform,drum,drumstick,dumbbell,Dutch_oven,electric_fan,electric_guitar,electric_locomotive,entertainment_center,envelope,espresso_maker,face_powder,feather_boa,file,fireboat,fire_engine,fire_screen,flagpole,flute,folding_chair,football_helmet,forklift,fountain,fountain_pen,four-poster,freight_car,French_horn,frying_pan,fur_coat,garbage_truck,gasmask,gas_pump,goblet,go-kart,golf_ball,golfcart,gondola,gong,gown,grand_piano,greenhouse,grille,grocery_store,guillotine,hair_slide,hair_spray,half_track,hammer,hamper,hand_blower,hand-held_computer,handkerchief,hard_disc,harmonica,harp,harvester,hatchet,holster,home_theater,honeycomb,hook,hoopskirt,horizontal_bar,horse_cart,hourglass,iPod,iron,jack-o'-lantern,jean,jeep,jersey,jigsaw_puzzle,jinrikisha,joystick,kimono,knee_pad,knot,lab_coat,ladle,lampshade,laptop,lawn_mower,lens_cap,letter_opener,library,lifeboat,lighter,limousine,liner,lipstick,Loafer,lotion,loudspeaker,loupe,lumbermill,magnetic_compass,mailbag,mailbox,maillot_(tights),maillot_(tank_suit),manhole_cover,maraca,marimba,mask,matchstick,maypole,maze,measuring_cup,medicine_chest,megalith,microphone,microwave,military_uniform,milk_can,minibus,miniskirt,minivan,missile,mitten,mixing_bowl,mobile_home,Model_T,modem,monastery,monitor,moped,mortar,mortarboard,mosque,mosquito_net,motor_scooter,mountain_bike,mountain_tent,mouse,mousetrap,moving_van,muzzle,nail,neck_brace,necklace,nipple,notebook,obelisk,oboe,ocarina,odometer,oil_filter,organ,oscilloscope,overskirt,oxcart,oxygen_mask,packet,paddle,paddlewheel,padlock,paintbrush,pajama,palace,panpipe,paper_towel,parachute,parallel_bars,park_bench,parking_meter,passenger_car,patio,pay-phone,pedestal,pencil_box,pencil_sharpener,perfume,Petri_dish,photocopier,pick,pickelhaube,picket_fence,pickup,pier,piggy_bank,pill_bottle,pillow,ping-pong_ball,pinwheel,pirate,pitcher,plane,planetarium,plastic_bag,plate_rack,plow,plunger,Polaroid_camera,pole,police_van,poncho,pool_table,pop_bottle,pot,potter,s_wheel,power_drill,prayer_rug,printer,prison,projectile,projector,puck,punching_bag,purse,quill,quilt,racer,racket,radiator,radio,radio_telescope,rain_barrel,recreational_vehicle,reel,reflex_camera,refrigerator,remote_control,restaurant,revolver,rifle,rocking_chair,rotisserie,rubber_eraser,rugby_ball,rule,running_shoe,safe,safety_pin,saltshaker,sandal,sarong,sax,scabbard,scale,school_bus,schooner,scoreboard,screen,screw,screwdriver,seat_belt,sewing_machine,shield,shoe_shop,shoji,shopping_basket,shopping_cart,shovel,shower_cap,shower_curtain,ski,ski_mask,sleeping_bag,slide_rule,sliding_door,slot,snorkel,snowmobile,snowplow,soap_dispenser,soccer_ball,sock,solar_dish,sombrero,soup_bowl,space_bar,space_heater,space_shuttle,spatula,speedboat,spider_web,spindle,sports_car,spotlight,stage,steam_locomotive,steel_arch_bridge,steel_drum,stethoscope,stole,stone_wall,stopwatch,stove,strainer,streetcar,stretcher,studio_couch,stupa,submarine,suit,sundial,sunglass,sunglasses,sunscreen,suspension_bridge,swab,sweatshirt,swimming_trunks,swing,switch,syringe,table_lamp,tank,tape_player,teapot,teddy,television,tennis_ball,thatch,theater_curtain,thimble,thresher,throne,tile_roof,toaster,tobacco_shop,toilet_seat,torch,totem_pole,tow_truck,toyshop,tractor,trailer_truck,tray,trench_coat,tricycle,trimaran,tripod,triumphal_arch,trolleybus,trombone,tub,turnstile,typewriter_keyboard,umbrella,unicycle,upright,vacuum,vase,vault,velvet,vending_machine,vestment,viaduct,violin,volleyball,waffle_iron,wall_clock,wallet,wardrobe,warplane,washbasin,washer,water_bottle,water_jug,water_tower,whiskey_jug,whistle,wig,window_screen,window_shade,Windsor_tie,wine_bottle,wing,wok,wooden_spoon,wool,worm_fence,wreck,yawl,yurt,web_site,comic_book,crossword_puzzle,street_sign,traffic_light,book_jacket,menu,plate,guacamole,consomme,hot_pot,trifle,ice_cream,ice_lolly,French_loaf,bagel,pretzel,cheeseburger,hotdog,mashed_potato,head_cabbage,broccoli,cauliflower,zucchini,spaghetti_squash,acorn_squash,butternut_squash,cucumber,artichoke,bell_pepper,cardoon,mushroom,Granny_Smith,strawberry,orange,lemon,fig,pineapple,banana,jackfruit,custard_apple,pomegranate,hay,carbonara,chocolate_sauce,dough,meat_loaf,pizza,potpie,burrito,red_wine,espresso,cup,eggnog,alp,bubble,cliff,coral_reef,geyser,lakeside,promontory,sandbar,seashore,valley,volcano,ballplayer,groom,scuba_diver,rapeseed,daisy,yellow_lady,s_slipper,corn,acorn,hip,buckeye,coral_fungus,agaric,gyromitra,stinkhorn,earthstar,hen-of-the-woods,bolete,ear,toilet_tissue",
    splitter: '0,0,0,0',
    client: '9669d4dcfa771f83',
    x: 490,
    y: 160,
    wires: [['4e1a43d2538436f3']],
  },
  {
    id: 'b70b2b7d82b22468',
    type: 'ui-template',
    z: '538995f1eb11573a',
    group: 'ce9b7d631b15dfcf',
    name: 'Preview Page',
    order: 1,
    width: 0,
    height: 0,
    head: '',
    format:
      '<template>\n  <div :id="containerId" style="width: 100%; height: 100%;">\n    <svg :id="svgId" ref="svgEl" style="display: block"></svg>\n    <p v-if="connectionStatus" :style="{ color: connectionStatus === \'Connected\' ? \'green\' : \'red\' }">\n      WebSocket: {{ connectionStatus }}\n    </p>\n  </div>\n</template>\n\n<script>\nexport default {\n  data() {\n    return {\n      ws: null,\n      connectionStatus: "Disconnected",\n      socketURL: `ws://${window.location.hostname}:8090`,\n      previewData: null,\n      svgWidth: 1920,\n      svgHeight: 1080,\n      reconnectTimer: null,\n      isDestroyed: false,\n    };\n  },\n  computed: {\n    containerId() { return `container`; },\n    svgId() { return `svg`; },\n  },\n  methods: {\n    updateSvgViewBox() {\n      const svg = this.$refs?.svgEl;\n      if (svg) svg.setAttribute("viewBox", `0 50 ${this.svgWidth} ${this.svgHeight}`);\n    },\n    initializeWebSocket() {\n      if (this.reconnectTimer) { clearTimeout(this.reconnectTimer); this.reconnectTimer = null; }\n      if (this.ws) this.ws.close();\n      if (this.isDestroyed) return;\n\n      this.ws = new WebSocket(this.socketURL);\n      this.ws.binaryType = "arraybuffer";\n\n      this.ws.addEventListener("open", () => { if (!this.isDestroyed) this.connectionStatus = "Connected"; });\n      this.ws.addEventListener("message", (event) => {\n        if (this.isDestroyed) return;\n        try {\n          const uint8Array = new Uint8Array(event.data);\n          const string = new TextDecoder().decode(uint8Array);\n          const obj = JSON.parse(string);\n          this.previewData = obj.data || obj;\n          const res = this.previewData?.resolution;\n          if (Array.isArray(res) && Number.isFinite(res[0]) && Number.isFinite(res[1])) {\n            this.svgWidth = res[0];\n            this.svgHeight = res[1];\n            this.updateSvgViewBox();\n          }\n          this.$nextTick(() => this.renderAll());\n        } catch (e) {\n          console.error("Error processing data:", e);\n        }\n      });\n      this.ws.addEventListener("error", (e) => {\n        console.error("WebSocket Error:", e);\n        if (!this.isDestroyed) this.connectionStatus = "Error";\n      });\n      this.ws.addEventListener("close", () => {\n        if (!this.isDestroyed) {\n          this.connectionStatus = "Disconnected";\n          this.reconnectTimer = setTimeout(() => { if (!this.isDestroyed) this.initializeWebSocket(); }, 5000);\n        }\n      });\n    },\n    createSVGElement(type, attributes = {}) {\n      const el = document.createElementNS("http://www.w3.org/2000/svg", type);\n      Object.keys(attributes).forEach((k) => el.setAttribute(k, attributes[k]));\n      return el;\n    },\n    getColor(index, opacity = 1) {\n      const COLORS = ["#FF0000","#FF8C00","#FFD700","#32CD32","#006400","#4169E1","#1E90FF","#00CED1","#FF1493","#800080"];\n      const color = COLORS[index % COLORS.length];\n      if (opacity < 1 && opacity >= 0) {\n        const r = parseInt(color.slice(1,3),16);\n        const g = parseInt(color.slice(3,5),16);\n        const b = parseInt(color.slice(5,7),16);\n        return `rgba(${r}, ${g}, ${b}, ${opacity})`;\n      }\n      return color;\n    },\n    renderImage(svg, group, data) {\n      if (data.image) {\n        let img = document.getElementById(`image-output-img`);\n        if (!img) {\n          img = this.createSVGElement("image", { id:`image-output-img`, x:"0", y:"50" });\n          svg.prepend(img);\n        }\n        img.setAttribute("href", `data:image/jpeg;base64,${data.image}`);\n      }\n    },\n    renderBoxes(group, data) {\n      if (!Array.isArray(data?.boxes)) return;\n      const fontSize = (data.resolution?.[1] || 1080) / 24;\n      data.boxes.forEach((box, i) => {\n        if (!Array.isArray(box) || box.length !== 6) return;\n        const [x,y,w,h,score,tar] = box;\n        const color = this.getColor(tar);\n        const label = data.labels?.[i] ?? `cls-${tar}`;\n        const rect = this.createSVGElement("rect", {\n          x: x - w/2, y: y - h/2, width: w, height: h,\n          fill: "none", stroke: color, "stroke-width":"2"\n        });\n        group.appendChild(rect);\n\n        const lh = fontSize + 4;\n        const lx = x - w/2;\n        const ly = (y - h/2 < lh) ? (y - h/2) : (y - h/2 - lh);\n        const bg = this.createSVGElement("rect", { x: lx, y: ly, width: w, height: lh, fill: color, stroke: color, "stroke-width":"2" });\n        group.appendChild(bg);\n\n        const txt = this.createSVGElement("text", { x: lx + 5, y: ly + lh - 4, "font-size": fontSize, fill:"white", "font-family":"Arial" });\n        txt.textContent = `${label} (${score})`;\n        group.appendChild(txt);\n      });\n    },\n    renderAll() {\n      const svg = this.$refs?.svgEl || document.getElementById(this.svgId);\n      if (!svg || !this.previewData) return;\n      let group = document.getElementById(`image-output-group`);\n      if (!group) {\n        group = this.createSVGElement("g", { id:`image-output-group`, transform:"translate(0, 50)" });\n        svg.appendChild(group);\n      }\n      group.innerHTML = "";\n      this.renderImage(svg, group, this.previewData);\n      this.renderBoxes(group, this.previewData);\n    },\n  },\n  mounted() {\n    this.isDestroyed = false;\n    this.initializeWebSocket();\n  },\n  unmounted() {\n    this.isDestroyed = true;\n    if (this.reconnectTimer) { clearTimeout(this.reconnectTimer); this.reconnectTimer = null; }\n    if (this.ws) { this.ws.close(); this.ws = null; }\n  },\n};\n</script>\n\n<style>\n  #container { position: relative; width: 100%; height: 100%; }\n  svg { width: 100%; height: 100%; background-color: #000; }\n  p {\n    position: absolute; bottom: 10px; left: 10px; margin: 0; padding: 5px;\n    background-color: rgba(0, 0, 0, 0.5); border-radius: 4px;\n  }\n</style>',
    storeOutMessages: true,
    passthru: true,
    resendOnRefresh: true,
    templateScope: 'local',
    className: '',
    x: 740,
    y: 120,
    wires: [[]],
  },
  {
    id: 'c6bf90ad353200e0',
    type: 'ui-template',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    name: 'Current Model (fetch)',
    order: 1,
    width: '3',
    height: '1',
    head: '',
    format:
      '<template><div style="display:none"></div></template>\n<script>\n  export default {\n    data() { return { name: "" }; },\n    watch: { name() { this.send({payload: this.name}) } },\n    async mounted() {\n      const resp = await fetch(`http://${window.location.hostname}/api/deviceMgr/getModelInfo`);\n      const data = await resp.json();\n      try {\n        const modelInfo = JSON.parse(data.data.model_info);\n        this.name = modelInfo.model_name || "";\n      } catch (e) { this.name = ""; }\n    },\n  };\n</script>',
    storeOutMessages: true,
    passthru: true,
    resendOnRefresh: true,
    templateScope: 'local',
    className: '',
    x: 620,
    y: 440,
    wires: [['b6e2d47425429fbb']],
  },
  {
    id: 'b6e2d47425429fbb',
    type: 'ui-text',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    order: 2,
    name: 'Current Model',
    label: 'Current Model is:',
    format: '{{msg.payload}}',
    layout: 'row-left',
    style: false,
    font: '',
    fontSize: 16,
    color: '#717171',
    wrapText: false,
    className: '',
    x: 1020,
    y: 440,
    wires: [],
  },
  {
    id: '02adbcfe20194d28',
    type: 'ui-slider',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    name: 'Confidence',
    label: 'Confidence',
    order: 4,
    width: 0,
    height: 0,
    passthru: false,
    outs: 'all',
    topic: 'topic',
    topicType: 'msg',
    thumbLabel: 'true',
    showTicks: 'always',
    min: 0,
    max: '100',
    step: 1,
    className: '',
    showTextField: false,
    x: 170,
    y: 360,
    wires: [['42fc40d9317f1f8d']],
  },
  {
    id: '42fc40d9317f1f8d',
    type: 'function',
    z: '538995f1eb11573a',
    name: 'Send Confidence',
    func: 'const tscore = Number((Number(msg.payload)/100).toFixed(2));\nmsg.payload = {tscore};\nreturn msg;',
    outputs: 1,
    timeout: 0,
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 380,
    y: 360,
    wires: [['57e1fa1fdbf4161a']],
  },
  {
    id: 'd085d476f78b4079',
    type: 'switch',
    z: '538995f1eb11573a',
    name: 'Light Switch',
    property: 'payload',
    propertyType: 'msg',
    rules: [
      { t: 'eq', v: 'on', vt: 'str' },
      { t: 'eq', v: 'off', vt: 'str' },
    ],
    checkall: 'true',
    repair: false,
    outputs: 2,
    x: 590,
    y: 700,
    wires: [['68d420b84a737965'], ['68d420b84a737965']],
  },
  {
    id: '68d420b84a737965',
    type: 'light',
    z: '538995f1eb11573a',
    light: false,
    x: 910,
    y: 680,
    wires: [],
  },
  {
    id: '348b1462c7bde706',
    type: 'inject',
    z: '538995f1eb11573a',
    name: 'Light ON',
    props: [{ p: 'payload' }, { p: 'topic', vt: 'str' }],
    repeat: '',
    crontab: '',
    once: false,
    onceDelay: 0.1,
    topic: '',
    payload: 'on',
    payloadType: 'str',
    x: 220,
    y: 600,
    wires: [['d085d476f78b4079']],
  },
  {
    id: 'f235556a2d602550',
    type: 'inject',
    z: '538995f1eb11573a',
    name: 'Light OFF',
    props: [{ p: 'payload' }, { p: 'topic', vt: 'str' }],
    repeat: '',
    crontab: '',
    once: false,
    onceDelay: 0.1,
    topic: '',
    payload: 'off',
    payloadType: 'str',
    x: 240,
    y: 720,
    wires: [['d085d476f78b4079']],
  },
  {
    id: '4e1a43d2538436f3',
    type: 'function',
    z: '538995f1eb11573a',
    name: 'handle classes percents',
    func: 'const p = msg.payload || {};\nconst d = p.data || {};\n\nconst classesArr = Array.isArray(d.classes) ? d.classes : [];\nconst labelsArr  = Array.isArray(d.labels)  ? d.labels  : [];\n\nconst classPercents = {};\nconst topk = [];\n\nfor (let i = 0; i < classesArr.length; i++) {\n  const item = classesArr[i] || [];\n  const score = item[0];\n  const classId = item[1];\n\n  const percent = Number.isFinite(+score)\n    ? Math.max(0, Math.min(100, Math.round(+score)))\n    : 0;\n\n  const label = labelsArr[i] ?? (classId !== undefined ? `Class ${classId}` : `Class ${i + 1}`);\n\n  const rec = { rank: i + 1, label: String(label), percent, classId };\n  topk.push(rec);\n  classPercents[rec.label] = rec.percent;\n}\n\n// 这里 topk 仍可保留（便于你之后做 topk 面板），但 B 模式 UI 主要用 classPercents\nmsg.payload = {\n  classPercents,\n  topk,                 // 可选保留\n  top1: topk[0] || null,\n  perf: d.perf || [],\n  resolution: d.resolution || []\n};\n\nreturn msg;\n',
    outputs: 1,
    timeout: 0,
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 650,
    y: 240,
    wires: [['3b47eb7abf489a8e']],
  },
  {
    id: '3b47eb7abf489a8e',
    type: 'ui-template',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    page: '',
    ui: '',
    name: 'classes confs',
    order: 0,
    width: 0,
    height: 0,
    head: '',
    format:
      '<template>\n  <div class="wrap">\n    <div class="model-line">\n      Current Model is: <span class="model-name">{{ modelName }}</span>\n    </div>\n\n    <div class="title">Preview</div>\n\n    <div class="rows">\n      <div v-for="(row, idx) in rows" :key="row.key" class="row">\n        <div class="bar-bg">\n          <div class="bar-fill" :style="fillStyle(row, idx)">\n            <span class="pct">{{ row.percent }}%</span>\n          </div>\n        </div>\n        <div class="label" :title="row.label">{{ row.label }}</div>\n      </div>\n    </div>\n  </div>\n</template>\n\n<script>\n  export default {\n    data() {\n      return {\n        modelName: \'\',\n        rows: [], // 固定渲染：所有类\n        classIndex: new Map(), // label -> row index\n        palette: [\'#9B6DFF\', \'#3F9DFF\', \'#FF8A00\', \'#34C759\', \'#AF52DE\'],\n        _modelPollTimer: null,\n      };\n    },\n\n    mounted() {\n      this.loadModelInfo();\n      // 如果你切换模型后 UI 需要自动刷新类表，可以轮询（可按需关掉）\n      this._modelPollTimer = setInterval(() => this.loadModelInfo(), 5000);\n    },\n\n    unmounted() {\n      if (this._modelPollTimer) clearInterval(this._modelPollTimer);\n      this._modelPollTimer = null;\n    },\n\n    watch: {\n      msg: {\n        immediate: true,\n        deep: true,\n        handler(m) {\n          const p = m?.payload ?? m ?? {};\n          const map =\n            p?.classPercents && typeof p.classPercents === \'object\'\n              ? p.classPercents\n              : {};\n\n          if (!this.rows || !this.rows.length) return;\n\n          // 全量类固定显示：对每个 row，用 map 覆盖；没给到就是 0\n          for (let i = 0; i < this.rows.length; i++) {\n            const label = this.rows[i].label;\n            const v = map[label];\n            const percent = Number.isFinite(+v)\n              ? Math.max(0, Math.min(100, Math.round(+v)))\n              : 0;\n            this.rows[i].percent = percent;\n          }\n\n          this.rows.sort((a, b) => (b.percent - a.percent) || (a.idx - b.idx));\n        },\n      },\n    },\n\n    methods: {\n      async loadModelInfo() {\n        try {\n          const resp = await fetch(\n            `http://${window.location.hostname}/api/deviceMgr/getModelInfo`,\n          );\n          const data = await resp.json();\n\n          let modelInfo = null;\n          try {\n            modelInfo = JSON.parse(data?.data?.model_info || \'{}\');\n          } catch (e) {\n            modelInfo = null;\n          }\n\n          const newName = String(modelInfo?.model_name || \'\');\n          const classes = Array.isArray(modelInfo?.classes)\n            ? modelInfo.classes\n            : [];\n\n          // 更新标题\n          this.modelName = newName;\n\n          // 如果 classes 变化，则重建 rows（保持顺序、固定行数）\n          if (classes.length > 0 && this.shouldRebuildRows(classes)) {\n            this.buildRowsFromClasses(classes);\n          }\n        } catch (e) {\n          // 网络/接口失败时不崩，保留旧 UI\n        }\n      },\n\n      shouldRebuildRows(classes) {\n        if (this.rows.length !== classes.length) return true;\n        for (let i = 0; i < classes.length; i++) {\n          if (this.rows[i]?.label !== String(classes[i])) return true;\n        }\n        return false;\n      },\n\n      buildRowsFromClasses(classes) {\n        this.rows = classes.map((label, i) => ({\n          key: `${label}-${i}`,\n          label: String(label),\n          percent: 0,\n        }));\n        this.classIndex = new Map();\n        this.rows.forEach((r, i) => this.classIndex.set(r.label, i));\n      },\n\n      clampPercent(v) {\n        const n = Number(v);\n        if (!Number.isFinite(n)) return 0;\n        return Math.max(0, Math.min(100, Math.round(n)));\n      },\n\n      // 给每个类一个稳定颜色（同 label 恒定）\n      colorForLabel(label) {\n        const s = String(label ?? \'\');\n        let h = 0;\n        for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;\n        return this.palette[h % this.palette.length];\n      },\n\n      fillStyle(row) {\n        return {\n          width: `${this.clampPercent(row.percent)}%`,\n          background: this.colorForLabel(row.label),\n        };\n      },\n    },\n  };\n</script>\n\n<style>\n  .wrap {\n    width: 100%;\n    padding: 8px 4px;\n  }\n\n  .model-line {\n    font-size: 22px;\n    font-weight: 600;\n    margin: 4px 0 10px 0;\n  }\n\n  .model-name {\n    font-weight: 800;\n  }\n\n  .title {\n    text-align: center;\n    font-size: 40px;\n    font-weight: 900;\n    margin: 8px 0 18px 0;\n  }\n\n  .rows {\n    display: flex;\n    flex-direction: column;\n    gap: 18px;\n  }\n\n  .row {\n    display: flex;\n    align-items: center;\n    gap: 22px;\n  }\n\n  .bar-bg {\n    flex: 1;\n    height: 54px;\n    background: #eef1f6;\n    border-radius: 10px;\n    overflow: hidden;\n  }\n\n  .bar-fill {\n    height: 100%;\n    border-radius: 10px;\n    display: flex;\n    align-items: center;\n    justify-content: flex-end;\n    padding-right: 16px;\n    box-sizing: border-box;\n    transition: width 180ms ease;\n  }\n\n  .pct {\n    color: #fff;\n    font-size: 26px;\n    font-weight: 900;\n    line-height: 1;\n  }\n\n  .label {\n    width: 240px;\n    font-size: 38px;\n    font-weight: 500;\n    color: #111;\n    white-space: nowrap;\n    overflow: hidden;\n    text-overflow: ellipsis;\n  }\n\n  /* 小屏适配 */\n  @media (max-width: 768px) {\n    .title {\n      font-size: 28px;\n    }\n\n    .bar-bg {\n      height: 40px;\n    }\n\n    .pct {\n      font-size: 18px;\n    }\n\n    .label {\n      width: 160px;\n      font-size: 24px;\n    }\n\n    .model-line {\n      font-size: 16px;\n    }\n  }\n</style>\n',
    storeOutMessages: true,
    passthru: true,
    resendOnRefresh: true,
    templateScope: 'local',
    className: '',
    x: 900,
    y: 240,
    wires: [[]],
  },
  {
    id: '9669d4dcfa771f83',
    type: 'sscma',
    host: 'localhost',
    mqttport: '1883',
    apiport: '80',
    clientid: 'recamera',
    username: '',
    password: '',
  },
  {
    id: 'ce9b7d631b15dfcf',
    type: 'ui-group',
    name: 'Preview',
    page: '60c320de6626b32b',
    width: '6',
    height: '1',
    order: 1,
    showTitle: true,
    className: '',
    visible: 'true',
    disabled: 'false',
    groupType: 'default',
  },
  {
    id: '5ca0ec8761494d59',
    type: 'ui-group',
    name: 'Model & Controls',
    page: '60c320de6626b32b',
    width: '6',
    height: '1',
    order: 2,
    showTitle: false,
    className: '',
    visible: 'true',
    disabled: 'false',
    groupType: 'default',
  },
  {
    id: '60c320de6626b32b',
    type: 'ui-page',
    name: 'Preview',
    ui: '1659e8381d2c4c07',
    path: '/preview',
    icon: 'home',
    layout: 'grid',
    theme: 'c18f6551f0ccec21',
    breakpoints: [
      { name: 'Default', px: '0', cols: '3' },
      { name: 'Tablet', px: '576', cols: '6' },
      { name: 'Small Desktop', px: '768', cols: '9' },
      { name: 'Desktop', px: '1024', cols: '12' },
    ],
    order: 1,
    className: '',
    visible: true,
    disabled: false,
  },
  {
    id: '1659e8381d2c4c07',
    type: 'ui-base',
    name: 'reCamera Dashboard',
    path: '/dashboard',
    appIcon: '',
    includeClientData: true,
    acceptsClientConfig: ['ui-notification', 'ui-control'],
    showPathInSidebar: false,
    navigationStyle: 'default',
    titleBarStyle: 'default',
    showReconnectNotification: true,
    notificationDisplayTime: 1,
    showDisconnectNotification: true,
  },
  {
    id: 'c18f6551f0ccec21',
    type: 'ui-theme',
    name: 'Default Theme',
    colors: {
      surface: '#ffffff',
      primary: '#0094ce',
      bgPage: '#eeeeee',
      groupBg: '#ffffff',
      groupOutline: '#cccccc',
    },
    sizes: {
      density: 'default',
      pagePadding: '12px',
      groupGap: '12px',
      groupBorderRadius: '4px',
      widgetGap: '12px',
    },
  },
  {
    id: '60bc2e2dc490eabe',
    type: 'global-config',
    env: [],
    modules: {
      'node-red-contrib-sscma': '0.3.6',
      '@flowfuse/node-red-dashboard': '1.26.0',
      'node-red-contrib-seeed-recamera': '0.0.8',
    },
  },
];

export const DefaultFlowDataWithDashboard = JSON.stringify(j);
