const j = [
  {
    id: '538995f1eb11573a',
    type: 'tab',
    label: 'reCamera Dashboard',
    disabled: false,
    info: '',
    env: [],
  },
  {
    id: 'ed8eabb66a7d65e6',
    type: 'camera',
    z: '538995f1eb11573a',
    client: '9669d4dcfa771f83',
    audio: false,
    volume: '50',
    option: '0',
    x: 240,
    y: 120,
    wires: [['57e1fa1fdbf4161a']],
  },
  {
    id: '57e1fa1fdbf4161a',
    type: 'model',
    z: '538995f1eb11573a',
    name: 'model',
    uri: '',
    model: 'YOLO11n Classify',
    tscore: '0.01',
    tiou: '0.01',
    debug: false,
    trace: false,
    counting: false,
    draw: false,
    classes: 'none,run,stop',
    splitter: '0,0,0,0',
    client: '9669d4dcfa771f83',
    x: 490,
    y: 160,
    wires: [['4e1a43d2538436f3']],
  },
  {
    id: 'b70b2b7d82b22468',
    type: 'ui-template',
    z: '538995f1eb11573a',
    group: 'ce9b7d631b15dfcf',
    name: 'Preview Page',
    order: 1,
    width: 0,
    height: 0,
    head: '',
    format:
      '<template>\n  <div :id="containerId" style="width: 100%; height: 100%;">\n    <svg :id="svgId" ref="svgEl" style="display: block"></svg>\n    <p v-if="connectionStatus" :style="{ color: connectionStatus === \'Connected\' ? \'green\' : \'red\' }">\n      WebSocket: {{ connectionStatus }}\n    </p>\n  </div>\n</template>\n\n<script>\nexport default {\n  data() {\n    return {\n      ws: null,\n      connectionStatus: "Disconnected",\n      socketURL: `ws://${window.location.hostname}:8090`,\n      previewData: null,\n      svgWidth: 1920,\n      svgHeight: 1080,\n      reconnectTimer: null,\n      isDestroyed: false,\n    };\n  },\n  computed: {\n    containerId() { return `container`; },\n    svgId() { return `svg`; },\n  },\n  methods: {\n    updateSvgViewBox() {\n      const svg = this.$refs?.svgEl;\n      if (svg) svg.setAttribute("viewBox", `0 50 ${this.svgWidth} ${this.svgHeight}`);\n    },\n    initializeWebSocket() {\n      if (this.reconnectTimer) { clearTimeout(this.reconnectTimer); this.reconnectTimer = null; }\n      if (this.ws) this.ws.close();\n      if (this.isDestroyed) return;\n\n      this.ws = new WebSocket(this.socketURL);\n      this.ws.binaryType = "arraybuffer";\n\n      this.ws.addEventListener("open", () => { if (!this.isDestroyed) this.connectionStatus = "Connected"; });\n      this.ws.addEventListener("message", (event) => {\n        if (this.isDestroyed) return;\n        try {\n          const uint8Array = new Uint8Array(event.data);\n          const string = new TextDecoder().decode(uint8Array);\n          const obj = JSON.parse(string);\n          this.previewData = obj.data || obj;\n          const res = this.previewData?.resolution;\n          if (Array.isArray(res) && Number.isFinite(res[0]) && Number.isFinite(res[1])) {\n            this.svgWidth = res[0];\n            this.svgHeight = res[1];\n            this.updateSvgViewBox();\n          }\n          this.$nextTick(() => this.renderAll());\n        } catch (e) {\n          console.error("Error processing data:", e);\n        }\n      });\n      this.ws.addEventListener("error", (e) => {\n        console.error("WebSocket Error:", e);\n        if (!this.isDestroyed) this.connectionStatus = "Error";\n      });\n      this.ws.addEventListener("close", () => {\n        if (!this.isDestroyed) {\n          this.connectionStatus = "Disconnected";\n          this.reconnectTimer = setTimeout(() => { if (!this.isDestroyed) this.initializeWebSocket(); }, 5000);\n        }\n      });\n    },\n    createSVGElement(type, attributes = {}) {\n      const el = document.createElementNS("http://www.w3.org/2000/svg", type);\n      Object.keys(attributes).forEach((k) => el.setAttribute(k, attributes[k]));\n      return el;\n    },\n    getColor(index, opacity = 1) {\n      const COLORS = ["#FF0000","#FF8C00","#FFD700","#32CD32","#006400","#4169E1","#1E90FF","#00CED1","#FF1493","#800080"];\n      const color = COLORS[index % COLORS.length];\n      if (opacity < 1 && opacity >= 0) {\n        const r = parseInt(color.slice(1,3),16);\n        const g = parseInt(color.slice(3,5),16);\n        const b = parseInt(color.slice(5,7),16);\n        return `rgba(${r}, ${g}, ${b}, ${opacity})`;\n      }\n      return color;\n    },\n    renderImage(svg, group, data) {\n      if (data.image) {\n        let img = document.getElementById(`image-output-img`);\n        if (!img) {\n          img = this.createSVGElement("image", { id:`image-output-img`, x:"0", y:"50" });\n          svg.prepend(img);\n        }\n        img.setAttribute("href", `data:image/jpeg;base64,${data.image}`);\n      }\n    },\n    renderBoxes(group, data) {\n      if (!Array.isArray(data?.boxes)) return;\n      const fontSize = (data.resolution?.[1] || 1080) / 24;\n      data.boxes.forEach((box, i) => {\n        if (!Array.isArray(box) || box.length !== 6) return;\n        const [x,y,w,h,score,tar] = box;\n        const color = this.getColor(tar);\n        const label = data.labels?.[i] ?? `cls-${tar}`;\n        const rect = this.createSVGElement("rect", {\n          x: x - w/2, y: y - h/2, width: w, height: h,\n          fill: "none", stroke: color, "stroke-width":"2"\n        });\n        group.appendChild(rect);\n\n        const lh = fontSize + 4;\n        const lx = x - w/2;\n        const ly = (y - h/2 < lh) ? (y - h/2) : (y - h/2 - lh);\n        const bg = this.createSVGElement("rect", { x: lx, y: ly, width: w, height: lh, fill: color, stroke: color, "stroke-width":"2" });\n        group.appendChild(bg);\n\n        const txt = this.createSVGElement("text", { x: lx + 5, y: ly + lh - 4, "font-size": fontSize, fill:"white", "font-family":"Arial" });\n        txt.textContent = `${label} (${score})`;\n        group.appendChild(txt);\n      });\n    },\n    renderAll() {\n      const svg = this.$refs?.svgEl || document.getElementById(this.svgId);\n      if (!svg || !this.previewData) return;\n      let group = document.getElementById(`image-output-group`);\n      if (!group) {\n        group = this.createSVGElement("g", { id:`image-output-group`, transform:"translate(0, 50)" });\n        svg.appendChild(group);\n      }\n      group.innerHTML = "";\n      this.renderImage(svg, group, this.previewData);\n      this.renderBoxes(group, this.previewData);\n    },\n  },\n  mounted() {\n    this.isDestroyed = false;\n    this.initializeWebSocket();\n  },\n  unmounted() {\n    this.isDestroyed = true;\n    if (this.reconnectTimer) { clearTimeout(this.reconnectTimer); this.reconnectTimer = null; }\n    if (this.ws) { this.ws.close(); this.ws = null; }\n  },\n};\n</script>\n\n<style>\n  #container { position: relative; width: 100%; height: 100%; }\n  svg { width: 100%; height: 100%; background-color: #000; }\n  p {\n    position: absolute; bottom: 10px; left: 10px; margin: 0; padding: 5px;\n    background-color: rgba(0, 0, 0, 0.5); border-radius: 4px;\n  }\n</style>',
    storeOutMessages: true,
    passthru: true,
    resendOnRefresh: true,
    templateScope: 'local',
    className: '',
    x: 740,
    y: 120,
    wires: [[]],
  },
  {
    id: 'c6bf90ad353200e0',
    type: 'ui-template',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    name: 'Current Model (fetch)',
    order: 1,
    width: '3',
    height: '1',
    head: '',
    format:
      '<template><div style="display:none"></div></template>\n<script>\n  export default {\n    data() { return { name: "" }; },\n    watch: { name() { this.send({payload: this.name}) } },\n    async mounted() {\n      const resp = await fetch(`http://${window.location.hostname}/api/deviceMgr/getModelInfo`);\n      const data = await resp.json();\n      try {\n        const modelInfo = JSON.parse(data.data.model_info);\n        this.name = modelInfo.model_name || "";\n      } catch (e) { this.name = ""; }\n    },\n  };\n</script>',
    storeOutMessages: true,
    passthru: true,
    resendOnRefresh: true,
    templateScope: 'local',
    className: '',
    x: 620,
    y: 440,
    wires: [['b6e2d47425429fbb']],
  },
  {
    id: 'b6e2d47425429fbb',
    type: 'ui-text',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    order: 2,
    name: 'Current Model',
    label: 'Current Model is:',
    format: '{{msg.payload}}',
    layout: 'row-left',
    style: false,
    font: '',
    fontSize: 16,
    color: '#717171',
    wrapText: false,
    className: '',
    x: 1020,
    y: 440,
    wires: [],
  },
  {
    id: '02adbcfe20194d28',
    type: 'ui-slider',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    name: 'Confidence',
    label: 'Confidence',
    order: 4,
    width: 0,
    height: 0,
    passthru: false,
    outs: 'all',
    topic: 'topic',
    topicType: 'msg',
    thumbLabel: 'true',
    showTicks: 'always',
    min: 0,
    max: '100',
    step: 1,
    className: '',
    showTextField: false,
    x: 170,
    y: 360,
    wires: [['42fc40d9317f1f8d']],
  },
  {
    id: '42fc40d9317f1f8d',
    type: 'function',
    z: '538995f1eb11573a',
    name: 'Send Confidence',
    func: 'const tscore = Number((Number(msg.payload)/100).toFixed(2));\nmsg.payload = {tscore};\nreturn msg;',
    outputs: 1,
    timeout: 0,
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 380,
    y: 360,
    wires: [['57e1fa1fdbf4161a']],
  },
  {
    id: 'd085d476f78b4079',
    type: 'switch',
    z: '538995f1eb11573a',
    name: 'Light Switch',
    property: 'payload',
    propertyType: 'msg',
    rules: [
      { t: 'eq', v: 'on', vt: 'str' },
      { t: 'eq', v: 'off', vt: 'str' },
    ],
    checkall: 'true',
    repair: false,
    outputs: 2,
    x: 590,
    y: 700,
    wires: [['68d420b84a737965'], ['68d420b84a737965']],
  },
  {
    id: '68d420b84a737965',
    type: 'light',
    z: '538995f1eb11573a',
    light: false,
    x: 910,
    y: 680,
    wires: [],
  },
  {
    id: '348b1462c7bde706',
    type: 'inject',
    z: '538995f1eb11573a',
    name: 'Light ON',
    props: [{ p: 'payload' }, { p: 'topic', vt: 'str' }],
    repeat: '',
    crontab: '',
    once: false,
    onceDelay: 0.1,
    topic: '',
    payload: 'on',
    payloadType: 'str',
    x: 220,
    y: 600,
    wires: [['d085d476f78b4079']],
  },
  {
    id: 'f235556a2d602550',
    type: 'inject',
    z: '538995f1eb11573a',
    name: 'Light OFF',
    props: [{ p: 'payload' }, { p: 'topic', vt: 'str' }],
    repeat: '',
    crontab: '',
    once: false,
    onceDelay: 0.1,
    topic: '',
    payload: 'off',
    payloadType: 'str',
    x: 240,
    y: 720,
    wires: [['d085d476f78b4079']],
  },
  {
    id: '4e1a43d2538436f3',
    type: 'function',
    z: '538995f1eb11573a',
    name: 'handle classes percents',
    func: 'const p = msg.payload || {};\nconst d = p.data || {};\n\nconst classesArr = Array.isArray(d.classes) ? d.classes : [];\nconst labelsArr  = Array.isArray(d.labels)  ? d.labels  : [];\n\nconst classPercents = {};\nconst topk = [];\n\nfor (let i = 0; i < classesArr.length; i++) {\n  const item = classesArr[i] || [];\n  const score = item[0];\n  const classId = item[1];\n\n  const percent = Number.isFinite(+score)\n    ? Math.max(0, Math.min(100, Math.round(+score)))\n    : 0;\n\n  const label = labelsArr[i] ?? (classId !== undefined ? `Class ${classId}` : `Class ${i + 1}`);\n\n  const rec = { rank: i + 1, label: String(label), percent, classId };\n  topk.push(rec);\n  classPercents[rec.label] = rec.percent;\n}\n\n// 这里 topk 仍可保留（便于你之后做 topk 面板），但 B 模式 UI 主要用 classPercents\nmsg.payload = {\n  classPercents,\n  topk,                 // 可选保留\n  top1: topk[0] || null,\n  perf: d.perf || [],\n  resolution: d.resolution || []\n};\n\nreturn msg;\n',
    outputs: 1,
    timeout: 0,
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 650,
    y: 240,
    wires: [['3b47eb7abf489a8e']],
  },
  {
    id: '3b47eb7abf489a8e',
    type: 'ui-template',
    z: '538995f1eb11573a',
    group: '5ca0ec8761494d59',
    page: '',
    ui: '',
    name: 'classes confs',
    order: 0,
    width: 0,
    height: 0,
    head: '',
    format:
      '<template>\n  <div class="wrap" style="height:auto; overflow:auto">\n    <div class="model-line">\n      Current Model is: <span class="model-name">{{ modelName }}</span>\n    </div>\n\n    <div class="title">Preview</div>\n\n    <div class="rows">\n      <div v-for="row in rows" :key="row.key" class="row">\n        <!-- 左侧：Class 名称（同色） -->\n        <div class="label" :title="row.label" :style="labelStyle(row)">\n          {{ row.label }}\n        </div>\n\n        <!-- 中间：进度条（底色淡化，填充为 pill） -->\n        <div class="bar-bg" :style="trackStyle(row)">\n          <div class="bar-fill" :style="fillStyle(row)"></div>\n        </div>\n\n        <!-- 右侧：百分比固定（稳定不跳） -->\n        <div class="pct-fixed" :style="pctFixedStyle(row)">\n          {{ row.percent }}%\n        </div>\n      </div>\n    </div>\n  </div>\n</template>\n\n<script>\n  export default {\n  data() {\n    return {\n      modelName: "",\n      rows: [],\n      classIndex: new Map(),\n      palette: ["#9B6DFF", "#3F9DFF", "#FF8A00", "#34C759", "#AF52DE"],\n      _modelPollTimer: null,\n    };\n  },\n\n  mounted() {\n    this.loadModelInfo();\n    this._modelPollTimer = setInterval(() => this.loadModelInfo(), 5000);\n\n    // 你原来的高度兜底逻辑保留\n    (() => {\n      const apply = () => {\n        const el = document.querySelector("#root .ant-app");\n        if (!el) return false;\n\n        const h =\n          window.CSS?.supports && CSS.supports("height", "-webkit-fill-available")\n            ? "-webkit-fill-available"\n            : "100vh";\n\n        el.style.height = h;\n        el.style.minHeight = "100vh";\n        return true;\n      };\n\n      if (apply()) return;\n\n      const mo = new MutationObserver(() => {\n        if (apply()) mo.disconnect();\n      });\n\n      mo.observe(document.documentElement, { childList: true, subtree: true });\n    })();\n  },\n\n  unmounted() {\n    if (this._modelPollTimer) clearInterval(this._modelPollTimer);\n    this._modelPollTimer = null;\n  },\n\n  watch: {\n    msg: {\n      immediate: true,\n      deep: true,\n      handler(m) {\n        const p = m?.payload ?? m ?? {};\n        const map =\n          p?.classPercents && typeof p.classPercents === "object"\n            ? p.classPercents\n            : {};\n\n        if (!this.rows?.length) return;\n\n        // ✅ 不排序：保持 classes 原始顺序，避免 UI 跳变\n        for (let i = 0; i < this.rows.length; i++) {\n          const label = this.rows[i].label;\n          const v = map[label];\n          this.rows[i].percent = Number.isFinite(+v)\n            ? Math.max(0, Math.min(100, Math.round(+v)))\n            : 0;\n        }\n      },\n    },\n  },\n\n  methods: {\n    async loadModelInfo() {\n      try {\n        const resp = await fetch(\n          `http://${window.location.hostname}/api/deviceMgr/getModelInfo`\n        );\n        const data = await resp.json();\n\n        let modelInfo = null;\n        try {\n          modelInfo = JSON.parse(data?.data?.model_info || "{}");\n        } catch (e) {\n          modelInfo = null;\n        }\n\n        const newName = String(modelInfo?.model_name || "");\n        const classes = Array.isArray(modelInfo?.classes) ? modelInfo.classes : [];\n\n        this.modelName = newName;\n\n        // classes 变化才重建（固定行）\n        if (classes.length > 0 && this.shouldRebuildRows(classes)) {\n          this.buildRowsFromClasses(classes);\n        }\n      } catch (e) {\n        // ignore\n      }\n    },\n\n    shouldRebuildRows(classes) {\n      if (this.rows.length !== classes.length) return true;\n      for (let i = 0; i < classes.length; i++) {\n        if (this.rows[i]?.label !== String(classes[i])) return true;\n      }\n      return false;\n    },\n\n    buildRowsFromClasses(classes) {\n      this.rows = classes.map((label, i) => ({\n        key: `${label}-${i}`,\n        label: String(label),\n        percent: 0,\n      }));\n      this.classIndex = new Map();\n      this.rows.forEach((r, i) => this.classIndex.set(r.label, i));\n    },\n\n    clampPercent(v) {\n      const n = Number(v);\n      if (!Number.isFinite(n)) return 0;\n      return Math.max(0, Math.min(100, Math.round(n)));\n    },\n\n    // 同 label 稳定颜色\n    colorForLabel(label) {\n      const s = String(label ?? "");\n      let h = 0;\n      for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;\n      return this.palette[h % this.palette.length];\n    },\n\n    // #RRGGBB -> rgba()\n    hexToRgba(hex, a) {\n      const h = String(hex || "").replace("#", "");\n      const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;\n      if (full.length !== 6) return `rgba(0,0,0,${a})`;\n      const r = parseInt(full.slice(0, 2), 16);\n      const g = parseInt(full.slice(2, 4), 16);\n      const b = parseInt(full.slice(4, 6), 16);\n      return `rgba(${r},${g},${b},${a})`;\n    },\n\n    labelStyle(row) {\n      const c = this.colorForLabel(row.label);\n      return { color: c };\n    },\n\n    // 轨道底色淡化（参考图）\n    trackStyle(row) {\n      const c = this.colorForLabel(row.label);\n      return {\n        background: this.hexToRgba(c, 0.12),\n      };\n    },\n\n    // 填充 pill（只变化宽度）\n    fillStyle(row) {\n      const p = this.clampPercent(row.percent);\n      const c = this.colorForLabel(row.label);\n      return {\n        width: `${p}%`,\n        background: c,\n      };\n    },\n\n    // 右侧百分比：同色 pill，0% 时灰色\n    pctFixedStyle(row) {\n      const p = this.clampPercent(row.percent);\n      const c = this.colorForLabel(row.label);\n      if (p === 0) {\n        return {\n          background: "rgba(0,0,0,0.06)",\n          color: "#111",\n          border: "1px solid rgba(0,0,0,0.06)",\n        };\n      }\n      return {\n        background: c,\n        color: "#fff",\n      };\n    },\n  },\n};\n</script>\n\n<style>\n  .wrap {\n    width: 100%;\n    padding: 10px 10px;\n  }\n\n  /* 顶部信息 */\n  .model-line {\n    font-size: 22px;\n    font-weight: 700;\n    margin: 4px 0 10px 0;\n  }\n\n  .model-name {\n    font-weight: 900;\n  }\n\n  .title {\n    text-align: center;\n    font-size: 44px;\n    font-weight: 900;\n    margin: 10px 0 22px 0;\n  }\n\n  .rows {\n    display: flex;\n    flex-direction: column;\n    gap: 18px;\n  }\n\n  /* ✅ 参考图布局：左 label / 中 bar / 右百分比（稳定不跳） */\n  .row {\n    display: grid;\n    grid-template-columns: 180px 1fr 110px;\n    /* label 列更短 */\n    align-items: center;\n    gap: 22px;\n  }\n\n  /* ✅ A 方案：label 固定宽 + clamp 自适应字体（必要时 ellipsis） */\n  .label {\n    width: 180px;\n    font-size: clamp(18px, 2.2vw, 34px);\n    font-weight: 700;\n    white-space: nowrap;\n    overflow: hidden;\n    text-overflow: ellipsis;\n  }\n\n  /* bar：圆角更大 + 内边距 -> 胶囊轨道 */\n  .bar-bg {\n    height: 56px;\n    border-radius: 18px;\n    box-sizing: border-box;\n    padding: 8px;\n    /* 让填充块有“内缩”效果 */\n    overflow: hidden;\n  }\n\n  /* fill：真正的 pill */\n  .bar-fill {\n    height: 100%;\n    border-radius: 14px;\n    transition: width 220ms cubic-bezier(0.2, 0.9, 0.2, 1);\n    box-shadow: 0 8px 18px rgba(0, 0, 0, 0.08);\n  }\n\n  /* 右侧百分比：固定位置的 pill */\n  .pct-fixed {\n    height: 44px;\n    border-radius: 14px;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n\n    font-size: 26px;\n    font-weight: 900;\n    font-variant-numeric: tabular-nums;\n  }\n\n  /* 小屏适配 */\n  @media (max-width: 768px) {\n    .title {\n      font-size: 30px;\n    }\n\n    .row {\n      grid-template-columns: 140px 1fr 72px;\n      gap: 14px;\n    }\n\n    .label {\n      width: 140px;\n      font-size: clamp(14px, 3.2vw, 22px);\n    }\n\n    .bar-bg {\n      height: 42px;\n      border-radius: 14px;\n      padding: 6px;\n    }\n\n    .bar-fill {\n      border-radius: 10px;\n      box-shadow: 0 6px 12px rgba(0, 0, 0, 0.08);\n    }\n\n    .pct-fixed {\n      height: 32px;\n      border-radius: 10px;\n      font-size: 16px;\n    }\n\n    .model-line {\n      font-size: 16px;\n    }\n  }\n</style>',
    storeOutMessages: true,
    passthru: true,
    resendOnRefresh: true,
    templateScope: 'local',
    className: '',
    x: 900,
    y: 240,
    wires: [[]],
  },
  {
    id: '9669d4dcfa771f83',
    type: 'sscma',
    host: 'localhost',
    mqttport: '1883',
    apiport: '80',
    clientid: 'recamera',
    username: '',
    password: '',
  },
  {
    id: 'ce9b7d631b15dfcf',
    type: 'ui-group',
    name: 'Preview',
    page: '60c320de6626b32b',
    width: '6',
    height: '1',
    order: 1,
    showTitle: true,
    className: '',
    visible: 'true',
    disabled: 'false',
    groupType: 'default',
  },
  {
    id: '5ca0ec8761494d59',
    type: 'ui-group',
    name: 'Model & Controls',
    page: '60c320de6626b32b',
    width: '6',
    height: '1',
    order: 2,
    showTitle: false,
    className: '',
    visible: 'true',
    disabled: 'false',
    groupType: 'default',
  },
  {
    id: '60c320de6626b32b',
    type: 'ui-page',
    name: 'Preview',
    ui: '1659e8381d2c4c07',
    path: '/preview',
    icon: 'home',
    layout: 'grid',
    theme: 'c18f6551f0ccec21',
    breakpoints: [
      { name: 'Default', px: '0', cols: '3' },
      { name: 'Tablet', px: '576', cols: '6' },
      { name: 'Small Desktop', px: '768', cols: '9' },
      { name: 'Desktop', px: '1024', cols: '12' },
    ],
    order: 1,
    className: '',
    visible: true,
    disabled: false,
  },
  {
    id: '1659e8381d2c4c07',
    type: 'ui-base',
    name: 'reCamera Dashboard',
    path: '/dashboard',
    appIcon: '',
    includeClientData: true,
    acceptsClientConfig: ['ui-notification', 'ui-control'],
    showPathInSidebar: false,
    navigationStyle: 'default',
    titleBarStyle: 'default',
    showReconnectNotification: true,
    notificationDisplayTime: 1,
    showDisconnectNotification: true,
  },
  {
    id: 'c18f6551f0ccec21',
    type: 'ui-theme',
    name: 'Default Theme',
    colors: {
      surface: '#ffffff',
      primary: '#0094ce',
      bgPage: '#eeeeee',
      groupBg: '#ffffff',
      groupOutline: '#cccccc',
    },
    sizes: {
      density: 'default',
      pagePadding: '12px',
      groupGap: '12px',
      groupBorderRadius: '4px',
      widgetGap: '12px',
    },
  },
  {
    id: 'b39be86db12cfea1',
    type: 'global-config',
    env: [],
    modules: {
      'node-red-contrib-sscma': '0.3.6',
      '@flowfuse/node-red-dashboard': '1.30.2',
      'node-red-contrib-seeed-recamera': '0.0.8',
    },
  },
];

export const DefaultFlowDataWithDashboard = JSON.stringify(j);
