# cp asound.conf /etc/asound.conf
# cp -d libasound_module_pcm_cvi_audio.so*  /usr/lib/alsa-lib/
# arecord -D vmic -r 16000 -c 1 -f S16_LE --buffer-size=6400 -d 5 vmic.wav
# aplay -D vplay -r 16000 -c 1 -f S16_LE --buffer-size=640 -d 5 vmic.wav

pcm.cvi_audio {
    type asym
    playback.pcm "vplay"
    capture.pcm "vmic"
}

pcm.vplay {
    type cvi_audio
    # file "/path/to/your/audio_file.wav"
}

# ctl.vplay {
#     type hw
#     card 1
# }

pcm.vmic {
    type cvi_audio
    # file "/path/to/your/audio_file.wav"
}

# ctl.vmic {
#     type hw
#     card 0
# }

