#!/bin/sh

### BEGIN INIT INFO
# Provides:          sscma-node
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start SSCMA Node at boot time
# Description:       Start SSCMA Node service.
### END INIT INFO

DAEMON=/usr/local/bin/sscma-node
DAEMON_OPTS=""
NAME=sscma-node
DESC="SSCMA Node Service"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER=root 

if [[ ":$LD_LIBRARY_PATH:" != *":/mnt/system/lib:"* ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/system/lib
fi

if [[ ":$LD_LIBRARY_PATH:" != *":/mnt/system/usr/lib:"* ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/system/usr/lib
fi

if [[ ":$LD_LIBRARY_PATH:" != *":/mnt/system/usr/lib/3rd:"* ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/system/usr/lib/3rd
fi

start() {
    echo "Starting $DESC: $NAME"
    if [ -f $PIDFILE ]; then
        echo "$NAME is already running."
    else
        start-stop-daemon -S -q -m -b -p $PIDFILE \
                --exec $DAEMON -- $DAEMON_OPTS
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    fi
}

stop() {
    echo "Stopping $DESC: $NAME"
    if [ -f $PIDFILE ]; then
        start-stop-daemon -K -q -p $PIDFILE
        rm -f $PIDFILE
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    else
        echo "$NAME is not running."
    fi
}

restart() {
    stop
    start
}

status() {
    if [ -f $PIDFILE ]; then
        echo "$NAME is running."
    else
        echo "$NAME is not running."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
