#!/bin/sh
### BEGIN INIT INFO
# Provides:          bt-init
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Background Bluetooth Initialization
### END INIT INFO

case "$1" in
  start)
    echo "[BT-INIT] Launching Bluetooth initializer in background..."
    nohup /usr/local/bin/bt-init-daemon.sh > /var/log/bt-init.log 2>&1 &
    ;;
  stop)
    echo "[BT-INIT] Killing Bluetooth initializer (if running)..."
    killall hciattach 2>/dev/null
    hciconfig hci0 down 2>/dev/null
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    ;;
esac

exit 0
