#!/bin/sh

DAEMON=supervisor
DAEMON_PATH=/usr/local/bin

SRC_FLOW="/usr/share/supervisor/flows.json"
DST_FLOW="/home/recamera/.node-red/flows.json"

SRC_MODEL="/usr/share/supervisor/models/yolo11n_detection_cv181x_int8.cvimodel"
SRC_INFO="/usr/share/supervisor/models/yolo11n_detection_cv181x_int8.json"
DST_MODEL="/userdata/MODEL/model.cvimodel"
DST_INFO="/userdata/MODEL/model.json"

SERVICE_FILE="/etc/avahi/services/sscma.service"

if [ ! -f $DST_FLOW ] || [ ! -s $DEST_FLOW ]; then
    if [ -f $SRC_FLOW ]; then
        mkdir -p /userdata/MODEL
        cp $SRC_FLOW $DST_FLOW
        cp $SRC_MODEL $DST_MODEL
        cp $SRC_INFO $DST_INFO
        sync
    fi
fi

if [ -d /userdata/ ] && [ ! -f $DST_MODEL ]; then
    if [ -f $SRC_MODEL ]; then
        mkdir -p /userdata/MODEL
        cp $SRC_MODEL $DST_MODEL
        cp $SRC_INFO $DST_INFO
        sync
    fi
fi

sn_value=$(fw_printenv sn | awk -F'=' '{print $NF}')

if [ -z "$sn_value" ]; then
    sn_value="0000000000000000"
fi

txt_record="<txt-record>sn=$sn_value</txt-record>"

if ! grep -q "$txt_record" "$SERVICE_FILE"; then
    sed -i '/<type>_sscma._tcp<\/type>/a \ \ \ \ '"$txt_record" "$SERVICE_FILE"
fi

/etc/init.d/S50avahi-daemon stop
sleep 0.1
/etc/init.d/S50avahi-daemon start

start() {
    printf 'Starting Supervisor Service: '
    PID="`pidof $DAEMON`"

    if [ "$PID" ]; then
        echo "$DAEMON is already running."
    else
        $DAEMON_PATH/$DAEMON >/dev/null 2>&1 &
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    fi
}

stop() {
    printf 'Stopping Supervisor Service: '
    PID="`pidof $DAEMON`"

    if [ "$PID" ]; then
        kill $PID
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    else
        echo "$DAEMON is not running."
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start|stop|restart)
        "$1";;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
