set(CPACK_GENERATOR "DEB")

if(NOT DEFINED PROJECT_DESCRIPTION)
    set(PROJECT_DESCRIPTION "${PROJECT_NAME}) for ${CMAKE_SYSTEM_NAME}")
endif()

if(NOT DEFINED PROJECT_VENDOR)
    set(PROJECT_VENDOR "Seeed Technology Co.,Ltd.")
endif()

if(NOT DEFINED PROJECT_CONTACT)
    set(PROJECT_CONTACT "techsupport@seeed.cc")
endif()

if(NOT DEFINED CPACK_DEBIAN_PACKAGE_MAINTAINER)
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${PROJECT_CONTACT})
endif()

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION ${PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_VENDOR ${PROJECT_VENDOR})
set(CPACK_PACKAGE_CONTACT ${PROJECT_CONTACT})

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "riscv64")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_DEBIAN_PACKAGE_MAINTAINER})


set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")

install(TARGETS ${PROJECT_NAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

if(EXISTS ${PROJECT_DIR}/rootfs AND IS_DIRECTORY ${PROJECT_DIR}/rootfs)
    install(DIRECTORY ${PROJECT_DIR}/rootfs/ DESTINATION / USE_SOURCE_PERMISSIONS)
endif()

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${PROJECT_DIR}/control/preinst;${PROJECT_DIR}/control/postinst;${PROJECT_DIR}/control/prerm;${PROJECT_DIR}/control/postrm")

include(CPack)